=== OneHalf3544/CalCubeTimer/src/main/resources/guiLayouts/layout.dtd
<!ELEMENT gui (panel,menubar)?>

<!ELEMENT panel (center|north|south|east|west|page_start|page_end|line_start|line_end|panel|scrollpane|splitpane|component|button|checkbox|label|selectablelabel|tabbedpane)*>
<!ELEMENT center (panel|splitpane|component|button|checkbox|label|selectablelabel|scrollpane|tabbedpane)?>
<!ELEMENT north (panel|splitpane|component|button|checkbox|label|selectablelabel|scrollpane|tabbedpane)?>
<!ELEMENT south (panel|splitpane|component|button|checkbox|label|selectablelabel|scrollpane|tabbedpane)?>
<!ELEMENT east (panel|splitpane|component|button|checkbox|label|selectablelabel|scrollpane|tabbedpane)?>
<!ELEMENT west (panel|splitpane|component|button|checkbox|label|selectablelabel|scrollpane|tabbedpane)?>
<!ELEMENT page_start (panel|splitpane|component|button|checkbox|label|selectablelabel|scrollpane|tabbedpane)?>
<!ELEMENT page_end (panel|splitpane|component|button|checkbox|label|selectablelabel|scrollpane|tabbedpane)?>
<!ELEMENT line_start (panel|splitpane|component|button|checkbox|label|selectablelabel|scrollpane|tabbedpane)?>
<!ELEMENT line_end (panel|splitpane|component|button|checkbox|label|selectablelabel|scrollpane|tabbedpane)?>

<!ELEMENT menubar (menu|glue|component|button|checkbox|label|selectablelabel)*>
<!ELEMENT menu (#PCDATA|menu|menuitem|separator|checkboxmenuitem|component)*>

<!ELEMENT scrollpane (panel|splitpane|component|button|checkbox|label|selectablelabel)?>
<!ATTLIST scrollpane verticalpolicy (always|never|asneeded) #IMPLIED>
<!ATTLIST scrollpane horizontalpolicy (always|never|asneeded) #IMPLIED>

<!ELEMENT tabbedpane (panel|component|button|checkbox|label|selectablelabel|tabbedpane)*>
<!-- The following name attribute is currently used only to give tabs in jtabbedpanes titles -->
<!ATTLIST panel name CDATA #IMPLIED>
<!ATTLIST component name CDATA #IMPLIED>
<!ATTLIST button name CDATA #IMPLIED>
<!ATTLIST checkbox name CDATA #IMPLIED>
<!ATTLIST label name CDATA #IMPLIED>
<!ATTLIST selectablelabel name CDATA #IMPLIED>
<!ATTLIST tabbedpane name CDATA #IMPLIED>

<!ELEMENT splitpane (panel)*>
<!ATTLIST splitpane drawcontinuous (true|false) #IMPLIED>
<!ATTLIST splitpane resizeweight CDATA #IMPLIED>
<!ATTLIST splitpane split (horizontal|vertical) #IMPLIED>

<!ELEMENT component EMPTY>
<!ELEMENT separator EMPTY>
<!ELEMENT glue EMPTY>
<!ELEMENT button (#PCDATA)>
<!ELEMENT checkbox (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT selectablelabel (#PCDATA)>
<!ELEMENT menuitem (#PCDATA)>
<!ELEMENT checkboxmenuitem (#PCDATA)>

<!ATTLIST panel layout (border|box|grid|flow) #IMPLIED>
<!ATTLIST panel orientation (horizontal|vertical|page|line) #IMPLIED>
<!ATTLIST panel hgap CDATA #IMPLIED>
<!ATTLIST panel vgap CDATA #IMPLIED>
<!ATTLIST panel rows CDATA #IMPLIED>
<!ATTLIST panel cols CDATA #IMPLIED>
<!ATTLIST panel border CDATA #IMPLIED>
<!ATTLIST panel align (left|right|center|leading|trailing) #IMPLIED>

<!ATTLIST component type CDATA #REQUIRED>

<!ATTLIST button nominsize (true|false) #IMPLIED>
<!-- This attribute for panels is to override the
	default behavior of giving panels a minimum size of zero -->
<!ATTLIST panel nominsize (true|false) #IMPLIED>

<!ATTLIST button action CDATA #IMPLIED>
<!ATTLIST checkbox action CDATA #IMPLIED>
<!ATTLIST menuitem action CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem action CDATA #IMPLIED>

<!ATTLIST panel alignmentX CDATA #IMPLIED>
<!ATTLIST component alignmentX CDATA #IMPLIED>
<!ATTLIST button alignmentX CDATA #IMPLIED>
<!ATTLIST checkbox alignmentX CDATA #IMPLIED>
<!ATTLIST menuitem alignmentX CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem alignmentX CDATA #IMPLIED>
<!ATTLIST label alignmentX CDATA #IMPLIED>
<!ATTLIST selectablelabel alignmentX CDATA #IMPLIED>

<!ATTLIST panel alignmentY CDATA #IMPLIED>
<!ATTLIST component alignmentY CDATA #IMPLIED>
<!ATTLIST button alignmentY CDATA #IMPLIED>
<!ATTLIST checkbox alignmentY CDATA #IMPLIED>
<!ATTLIST menuitem alignmentY CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem alignmentY CDATA #IMPLIED>
<!ATTLIST label alignmentY CDATA #IMPLIED>
<!ATTLIST selectablelabel alignmentY CDATA #IMPLIED>

<!ATTLIST component border CDATA #IMPLIED>
<!ATTLIST button border CDATA #IMPLIED>
<!ATTLIST checkbox border CDATA #IMPLIED>
<!ATTLIST menuitem border CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem border CDATA #IMPLIED>
<!ATTLIST label border CDATA #IMPLIED>
<!ATTLIST selectablelabel border CDATA #IMPLIED>

<!ATTLIST component opaque CDATA #IMPLIED>
<!ATTLIST button opaque CDATA #IMPLIED>
<!ATTLIST checkbox opaque CDATA #IMPLIED>
<!ATTLIST menuitem opaque CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem opaque CDATA #IMPLIED>

<!ATTLIST component background CDATA #IMPLIED>
<!ATTLIST button background CDATA #IMPLIED>
<!ATTLIST checkbox background CDATA #IMPLIED>
<!ATTLIST menuitem background CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem background CDATA #IMPLIED>

<!ATTLIST component foreground CDATA #IMPLIED>
<!ATTLIST button foreground CDATA #IMPLIED>
<!ATTLIST checkbox foreground CDATA #IMPLIED>
<!ATTLIST menuitem foreground CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem foreground CDATA #IMPLIED>

<!ATTLIST component preferredsize CDATA #IMPLIED>
<!ATTLIST button preferredsize CDATA #IMPLIED>
<!ATTLIST checkbox preferredsize CDATA #IMPLIED>
<!ATTLIST menuitem preferredsize CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem preferredsize CDATA #IMPLIED>
<!ATTLIST scrollpane preferredsize CDATA #IMPLIED>
<!ATTLIST panel preferredsize CDATA #IMPLIED>

<!ATTLIST selectablelabel editable (true|false) #IMPLIED>

<!ATTLIST menu mnemonic CDATA #IMPLIED>
<!ATTLIST glue orientation (horizontal|vertical) #IMPLIED>
<!ATTLIST separator orientation (horizontal|vertical) #IMPLIED>

=== OneHalf3544/CalCubeTimer/src/main/resources/guiLayouts/jnetcube.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE gui SYSTEM "layout.dtd">
<gui>
	<panel layout="border">
		<splitpane drawcontinuous="true" resizeweight=".8" split="horizontal">
			<panel layout="border">
				<center>
					<panel layout="box" orientation="page">
						<panel layout="box" orientation="horizontal">
							<panel layout="box" orientation="page">
								<component type="scrambleChooser"/>
								<component alignmentX=".5" type="stackmatStatusLabel"/>
								<panel> <!-- This is to prevent the grid layout from getting squished -->
									<panel layout="grid" cols="2">
										<label>Scramble length:</label>
										<component type="scrambleLength" />
										<label>Scramble number: </label>
										<component type="scrambleNumber"/>
									</panel>
								</panel>
								<component type="scrambleAttributes"/>
							</panel>
							<panel layout="box" orientation="page" preferredsize="500x100">
								<component border="Use this algorithm to scramble your cube;000000" type="scrambleArea"/>
							</panel>
						</panel>
						<component type="timerDisplay"/>
					</panel>
				</center>
				<south>
					<panel layout="box" orientation="page">
						<panel layout="box" orientation="line">
							<panel layout="border" border="Session Statistics">
								<center>
									<panel layout="box" orientation="page">
										<label>Recent Time: stats[session.time(recent)]</label>
										<label>Previous Time: stats[session.time(last)]</label>
										<label>Progress: stats[session.time(progress)] seconds</label>
										<panel preferredsize="10x15"/>
										<label>Cubes Solved: stats[session.solvecount(solved)]</label>
										<label>Session Average: stats[session.average] seconds</label>
									</panel>
								</center>
								<line_end>
									<panel layout="box" orientation="page">
										<button action="sessionAverage">Detail</button>
										<button action="addTime">Add Time</button>
										<button action="reset">Reset</button>
									</panel>
								</line_end>
							</panel>
							<panel layout="border" border="Rolling Average">
								<panel layout="box" orientation="page">
									<label>Current Average: stats[ra(0, recent)]</label>
									<label>Progress: stats[ra(0).progress]</label>
									<panel preferredsize="10x15"/>
									<label>Fastest Time: stats[ra(0, recent).time(best)]</label>
									<label>Slowest Time: stats[ra(0, recent).time(worst)]</label>
									<label>Standard Deviation: stats[ra(0, recent).sd]</label>
								</panel>
							</panel>
						</panel>
						<panel border="Best Average" layout="box" orientation="page">
							<button action="bestAverage0" alignmentX=".99">Details</button>
							<selectablelabel border=";000000" alignmentX=".99">
								<![CDATA[<html>Average: stats[ra(0, best)]<br/>Individual Times: stats[ra(0, best).list]</html>]]>
							</selectablelabel>
						</panel>
					</panel>
				</south>
			</panel>
			<panel nominsize="false" layout="border">
				<tabbedpane>
					<component name="Times" type="timesList"/>
					<component name="Sessions" type="sessionsList"/>
				</tabbedpane>
			</panel>
		</splitpane>
	</panel>
	<menubar>
		<menu mnemonic="f">File
			<menuitem action="bestAverage0">Save Best Average As</menuitem>
			<menuitem action="sessionAverage">Save Session Average As</menuitem>
			<separator/>
			<menuitem action="showConfiguration">Options...</menuitem>
			<separator/>
			<menuitem action="exit">Exit</menuitem>
		</menu>
		<menu mnemonic="t">Tools
			<menuitem action="importScrambles">Import Scrambles</menuitem>
			<menuitem action="exportScrambles">Scramble Generator</menuitem>
			<checkboxmenuitem action="togglescramblepopup">View Scramble</checkboxmenuitem>
		</menu>
		<menu mnemonic="o">CCT Options
			<component type="customGUIMenu"/>
			<menu mnemonic="k">Keyboard Timer
				<checkboxmenuitem action="keyboardTiming">Use keyboard timer</checkboxmenuitem>
				<checkboxmenuitem action="toggleStatusLight">Use status light</checkboxmenuitem>
				<checkboxmenuitem action="toggleHideScrambles">Hide scrambles when timer not focused</checkboxmenuitem>
				<checkboxmenuitem action="toggleSpacebarStartsTimer">Only spacebar starts timer</checkboxmenuitem>
				<checkboxmenuitem action="toggleFullscreenTiming">Fullscreen while timing</checkboxmenuitem>
			</menu>
		</menu>
		<menu mnemonic="h">Help
			<menuitem action="showAbout">About</menuitem>
		</menu>
		<glue orientation="horizontal"/>
		<component type="profilecombobox"/>
		<button nominsize="true" action="togglefullscreen"/>
	</menubar>
</gui>

=== OneHalf3544/CalCubeTimer/src/main/resources/guiLayouts/cct.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE gui SYSTEM "layout.dtd">
<gui>
	<panel layout="border">
		<splitpane drawcontinuous="true" resizeweight="1" split="horizontal">
			<panel layout="border">
				<center>
					<panel layout="box" orientation="page">
						<component type="timerDisplay"/>
						<component type="scrambleArea"/>
					</panel>
				</center>
				<south>
					<panel layout="box" orientation="page">
						<scrollpane verticalpolicy="never" horizontalpolicy="asneeded">
							<panel alignmentY=".5" layout="flow" hgap="5" vgap="5">
								<component type="stackmatStatusLabel"/>
								<component type="scrambleChooser"/>
								<component type="scrambleNumber"/>
								<component type="scrambleAttributes"/>
								<component type="scrambleGenerator"/>
							</panel>
						</scrollpane>
						<panel layout="border">
							<center><panel><checkbox alignmentX=".5" action="keyboardTiming">i18n[usekeyboard]</checkbox></panel></center>
							<line_end>
								<panel>
									<button action="newSession">i18n[newsession]</button>
									<button action="reset">i18n[clearsession]</button>
								</panel>
							</line_end>
						</panel>
						<panel layout="box" orientation="line">
							<panel border="i18n[seshstats]" layout="grid" cols="1">
								<panel layout="box" orientation="line">
									<label>i18n[raof] stats[ra(0).size]</label>
									<button action="currentAverage0"><![CDATA[<html><font color="config[Statistics_Color_currentAverage]">i18n[currave] stats[ra(0, recent)] stats[ra(0).progress|parens]</font></html>]]></button>
									<button action="bestAverage0"><![CDATA[<html><font color="config[Statistics_Color_bestRA]">i18n[bestra] stats[ra(0, best)]</font></html>]]></button>
								</panel>
								<panel layout="box" orientation="line">
									<label>i18n[raof] stats[ra(1).size]</label>
									<button action="currentAverage1"><![CDATA[<html><font color="config[Statistics_Color_currentAverage]">i18n[currave] stats[ra(1, recent)] stats[ra(1).progress|parens]</font></html>]]></button>
									<button action="bestAverage1"><![CDATA[<html><font color="config[Statistics_Color_bestRA]">i18n[bestra] stats[ra(1, best)]</font></html>]]></button>
								</panel>
								<panel layout="box" orientation="line">
									<label>stats[session.solvecount(solved)]/stats[session.solvecount(attempt)] (i18n[solves]/i18n[attempts])</label>
									<button action="sessionAverage"><![CDATA[<html>i18n[seshave] stats[session.average] stats[session.average.progress|parens]</html>]]></button>
								</panel>
							</panel>
							<panel border="i18n[history]" layout="box" orientation="page">
								<panel><label alignmentX=".5">i18n[bestever] stats[global.time(best)]</label></panel>
								<panel><label alignmentX=".5">i18n[bestraof] stats[ra(0).size]: stats[global.ra(0, best)]</label></panel>
								<panel><label alignmentX=".5">stats[global.solvecount(solved)]/stats[global.solvecount(attempt)] i18n[globalaverage] stats[global.average]</label></panel>
							</panel>
						</panel>
					</panel>
				</south>
			</panel>
			<panel nominsize="false" layout="border">
				<tabbedpane>
					<component name="i18n[times] (stats[session.puzzleType])" type="timesList"/>
					<component name="i18n[sessions]" type="sessionsList"/>
				</tabbedpane>
			</panel>
		</splitpane>
	</panel>
	<menubar>
		<menu mnemonic="f">i18n[file]
			<menuitem action="importScrambles">i18n[import]</menuitem>
			<menuitem action="exportScrambles">i18n[export]</menuitem>
			<separator/>
			<menuitem action="addTime">i18n[addtime]</menuitem>
			<separator/>
			<menuitem action="showConfiguration">i18n[configuration]</menuitem>
			<separator/>
			<menuitem action="exit">i18n[exit]</menuitem>
		</menu>
		<menu mnemonic="o">i18n[options]
			<checkboxmenuitem action="toggleScramblePopup">i18n[togglescramblepopup]</checkboxmenuitem>
			<menu mnemonic="k">i18n[keyboardtimer]
				<checkboxmenuitem action="keyboardTiming">i18n[usekeyboard]</checkboxmenuitem>
				<checkboxmenuitem action="toggleStatusLight">i18n[statuslight]</checkboxmenuitem>
				<checkboxmenuitem action="toggleHideScrambles">i18n[hidescrambles]</checkboxmenuitem>
				<checkboxmenuitem action="toggleSpacebarStartsTimer">i18n[spacebaronly]</checkboxmenuitem>
				<checkboxmenuitem action="toggleFullscreenTiming">i18n[fullscreentiming]</checkboxmenuitem>
			</menu>
			<component type="customGUIMenu"/>
		</menu>
		<glue orientation="horizontal"/>
		<component type="languagecombobox"/>
		<component type="profilecombobox"/>
		<glue orientation="horizontal"/>
		<menu mnemonic="h">i18n[help]
			<menuitem action="showDocumentation">i18n[documentation]</menuitem>
			<menuitem action="showAbout">i18n[about]</menuitem>
		</menu>
		<button nominsize="true" action="togglefullscreen">+</button>
	</menubar>
</gui>

=== OneHalf3544/CalCubeTimer/src/main/resources/guiLayouts/minimalist.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE gui SYSTEM "layout.dtd">
<gui>
	<panel layout="border">
			<panel layout="border">
				<center>
					<panel layout="box" orientation="page">
						<component type="timerDisplay"/>
						<component type="scrambleArea"/>
					</panel>
				</center>
				<south>
					<panel layout="grid" cols="2">
					<panel><label>Cubes solved: stats[session.solvecount(solved)]</label></panel>
					<panel/>
					<panel><button action="sessionAverage">Session</button></panel>
					<panel><button action="currentAverage0">Current i18n[raof] stats[ra(0).size]</button><button action="bestAverage0">Best i18n[raof] stats[ra(0).size]</button></panel>
					</panel>
				</south>
			</panel>
	</panel>
	<menubar>
		<menu mnemonic="f">i18n[file1
			<menuitem action="importScrambles">i18n[import]</menuitem>
			<menuitem action="exportScrambles">i18n[export]</menuitem>
			<separator/>
			<menuitem action="addTime">i18n[addtime]</menuitem>
			<separator/>
			<menuitem action="showConfiguration">i18n[configuration]</menuitem>
			<separator/>
			<menuitem action="exit">i18n[exit]</menuitem>
		</menu>
		<menu mnemonic="o">i18n[options]
			<checkboxmenuitem action="toggleScramblePopup">i18n[togglescramblepopup]</checkboxmenuitem>
			<menu mnemonic="k">i18n[keyboardtimer]
				<checkboxmenuitem action="keyboardTiming">i18n[usekeyboard]</checkboxmenuitem>
				<checkboxmenuitem action="toggleStatusLight">i18n[statuslight]</checkboxmenuitem>
				<checkboxmenuitem action="toggleHideScrambles">i18n[hidescrambles]</checkboxmenuitem>
				<checkboxmenuitem action="toggleSpacebarStartsTimer">i18n[spacebaronly]</checkboxmenuitem>
				<checkboxmenuitem action="toggleFullscreenTiming">i18n[fullscreentiming]</checkboxmenuitem>
			</menu>
			<component type="customGUIMenu"/>
		</menu>
		<glue orientation="horizontal"/>
		<component type="scrambleChooser"/>
		<component type="profilecombobox"/>
		<glue orientation="horizontal"/>
		<button action="newSession">i18n[newsession]</button><button action="reset">i18n[clearsession]</button>
		<glue orientation="horizontal"/>
		<menu mnemonic="h">i18n[help]
			<menuitem action="showDocumentation">i18n[documentation]</menuitem>
			<menuitem action="showAbout">i18n[about]</menuitem>
		</menu>
		<button nominsize="true" action="togglefullscreen">+</button>
	</menubar>
</gui>

=== OneHalf3544/CalCubeTimer/src/main/resources/guiLayouts/shelley.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE gui SYSTEM "layout.dtd">
<gui>
	<panel layout="border">
		<splitpane drawcontinuous="true" resizeweight="1" split="horizontal">
			<panel layout="border">
				<north>
					<scrollpane verticalpolicy="never" horizontalpolicy="asneeded">
						<panel layout="box" orientation="page">
							<panel alignmentY=".5" layout="flow" hgap="5" vgap="5">
								<component type="stackmatStatusLabel"/>
								<component type="scrambleChooser"/>
								<component type="scrambleGenerator"/>
								<button action="newSession">%%newsession%%</button>
						 		<button action="reset">%%clearsession%%</button>
							</panel>
							<panel>
								<checkbox alignmentX=".5" action="togglescramblepopup">Show scramble?</checkbox>
								<checkbox alignmentX=".5" action="keyboardTiming">%%usekeyboard%%</checkbox>
								<component type="scrambleAttributes"/>
							</panel>
						</panel>
					</scrollpane>
				</north>
				<center>
					<panel layout="box" orientation="page">
						<component type="timerDisplay"/>
						<component type="scrambleArea"/>
					</panel>
				</center>
				<south>
					<panel layout="box" orientation="page">

						<panel layout="box" orientation="line">
							<panel border="%%seshstats%%" layout="grid" hgap="2" vgap="2" cols="3">
								<label>%%raof%% $$ra(0).size$$</label>
								<button action="currentAverage0">%%currave%% $$ra(0, recent)$$ $$ra(0).progress|parens$$</button>
								<button action="bestAverage0">%%bestra%% $$ra(0, best)$$</button>
								
								<label>%%raof%% $$ra(1).size$$</label>
								<button action="currentAverage1">%%currave%% $$ra(1, recent)$$ $$ra(1).progress|parens$$</button>
								<button action="bestAverage1">%%bestra%% $$ra(1, best)$$</button>

								<label>Cubes solved: $$session.solvecount(solved)$$/$$session.solvecount(attempt)$$</label>
								<button action="sessionAverage">%%seshave%% $$session.average$$ $$session.average.progress|parens$$</button>
							</panel>
							<panel border="%%history%%" layout="grid" cols="1" vgap="2">
								<panel><label alignmentX=".5">%%bestever%% $$global.time(best)$$</label></panel>
								<panel><label alignmentX=".5">%%bestraof%% $$ra(0).size$$: $$global.ra(0, best)$$</label></panel>
								<panel><label alignmentX=".5">%%bestraof%% $$ra(1).size$$: $$global.ra(1, best)$$</label></panel>
								<panel><label alignmentX=".5">$$global.solvecount(solved)$$/$$global.solvecount(attempt)$$ %%globalaverage%% $$global.average$$</label></panel>
							</panel>
						</panel>
					</panel>
				</south>
			</panel>
			<panel nominsize="false" layout="border">
				<tabbedpane>
					<component name="%%times%%" type="timesList"/>
					<component name="%%sessions%%" type="sessionsList"/>
				</tabbedpane>
			</panel>
		</splitpane>
	</panel>
	<menubar>
		<menu mnemonic="f">%%file%%
			<menuitem action="importScrambles">%%import%%</menuitem>
			<menuitem action="exportScrambles">%%export%%</menuitem>
			<separator/>
			<menuitem action="addTime">%%addtime%%</menuitem>
			<separator/>
			<menuitem action="connectToServer">%%connect%%</menuitem>
			<separator/>
			<menuitem action="showConfiguration">%%configuration%%</menuitem>
			<separator/>
			<menuitem action="exit">%%exit%%</menuitem>
		</menu>
		<menu mnemonic="o">%%options%%
			<menuitem action="undo"/>
			<menuitem action="redo"/>
			<separator/>
			<checkboxmenuitem action="toggleScramblePopup">%%togglescramblepopup%%</checkboxmenuitem>
			<menu mnemonic="k">%%keyboardtimer%%
				<checkboxmenuitem action="keyboardTiming">%%usekeyboard%%</checkboxmenuitem>
				<checkboxmenuitem action="toggleStatusLight">%%statuslight%%</checkboxmenuitem>
				<checkboxmenuitem action="toggleHideScrambles">%%hidescrambles%%</checkboxmenuitem>
				<checkboxmenuitem action="toggleSpacebarStartsTimer">%%spacebaronly%%</checkboxmenuitem>
				<checkboxmenuitem action="toggleFullscreenTiming">%%fullscreentiming%%</checkboxmenuitem>
			</menu>
			<component type="customGUIMenu"/>
		</menu>
		<glue orientation="horizontal"/>
		<component type="languagecombobox"/>
		<component type="profilecombobox"/>
		<glue orientation="horizontal"/>
		<menu mnemonic="h">%%help%%
			<menuitem action="showDocumentation">%%documentation%%</menuitem>
			<menuitem action="showAbout">%%about%%</menuitem>
		</menu>
		<button nominsize="true" action="togglefullscreen">+</button>
	</menubar>
</gui>
